"""empty message

Revision ID: 24418579b705
Revises: b31989c58070
Create Date: 2026-01-27 19:51:27.325056

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '24418579b705'
down_revision = 'b31989c58070'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.alter_column('profile_picture',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=True)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=False))
        batch_op.drop_column('created_at')
        batch_op.drop_column('profile_pic')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('private_key',
               existing_type=sa.BLOB(),
               nullable=True)
        batch_op.alter_column('public_key',
               existing_type=sa.BLOB(),
               nullable=True)
        batch_op.alter_column('profile_picture',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('profile_picture',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=False)
        batch_op.alter_column('public_key',
               existing_type=sa.BLOB(),
               nullable=False)
        batch_op.alter_column('private_key',
               existing_type=sa.BLOB(),
               nullable=False)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', mysql.VARCHAR(length=1000), nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=False))
        batch_op.drop_column('created_date')

    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.alter_column('profile_picture',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=False)

    # ### end Alembic commands ###
