"""empty message

Revision ID: 38c0951cfc76
Revises: f8847757b963
Create Date: 2025-11-18 14:34:30.622454

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '38c0951cfc76'
down_revision = 'f8847757b963'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('helpee_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('jobs_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['helpee_id'], ['id'])
        batch_op.drop_column('requester_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requester_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('jobs_ibfk_2'), 'users', ['requester_id'], ['id'])
        batch_op.drop_column('helpee_id')

    # ### end Alembic commands ###
