"""empty message

Revision ID: 3b64d6a1b458
Revises: dfe33f4545f6
Create Date: 2025-12-08 12:59:19.480129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b64d6a1b458'
down_revision = 'dfe33f4545f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map_icon',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('icon_url', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('map_icon')
    # ### end Alembic commands ###
