"""empty message

Revision ID: 4a88edf02430
Revises: 5e1bb59e7076
Create Date: 2026-01-27 18:54:46.711597

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a88edf02430'
down_revision = '5e1bb59e7076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('jobs_ibfk_2'), type_='foreignkey')
        batch_op.drop_column('helper_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('helper_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('jobs_ibfk_2'), 'users', ['helper_id'], ['id'])

    # ### end Alembic commands ###
