"""empty message

Revision ID: 4c1a38d5ce83
Revises: 4a88edf02430
Create Date: 2026-01-27 19:29:08.984381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c1a38d5ce83'
down_revision = '4a88edf02430'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=1000), nullable=False))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aes_key', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('iv', sa.LargeBinary(), nullable=True))

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=1000), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('private_key', sa.LargeBinary(), nullable=False))
        batch_op.add_column(sa.Column('public_key', sa.LargeBinary(), nullable=False))
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=1000), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('public_key')
        batch_op.drop_column('private_key')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('iv')
        batch_op.drop_column('aes_key')

    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###
