"""empty message

Revision ID: b31989c58070
Revises: 4c1a38d5ce83
Create Date: 2026-01-27 19:31:30.932805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b31989c58070'
down_revision = '4c1a38d5ce83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('iv')
        batch_op.drop_column('aes_key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aes_key', sa.BLOB(), nullable=True))
        batch_op.add_column(sa.Column('iv', sa.BLOB(), nullable=True))

    # ### end Alembic commands ###
