"""empty message

Revision ID: c4762bcc12c2
Revises: 2dc69d6178c9
Create Date: 2026-02-26 13:33:35.917832

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c4762bcc12c2'
down_revision = '2dc69d6178c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_location', schema=None) as batch_op:
        batch_op.alter_column('lat',
               existing_type=mysql.DECIMAL(precision=9, scale=6),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('lng',
               existing_type=mysql.DECIMAL(precision=9, scale=6),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('created_date',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.LargeBinary(),
               existing_nullable=False)
        batch_op.alter_column('timestamp',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('created_date',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=6),
               existing_nullable=False)
        batch_op.alter_column('verified',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('verified',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('type',
               existing_type=sa.String(length=6),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=False)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('created_date',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('content',
               existing_type=sa.LargeBinary(),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=False)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('created_date',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('job_location', schema=None) as batch_op:
        batch_op.alter_column('lng',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=9, scale=6),
               existing_nullable=False)
        batch_op.alter_column('lat',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=9, scale=6),
               existing_nullable=False)

    # ### end Alembic commands ###
