"""empty message

Revision ID: c8d981fb65cd
Revises: 24418579b705
Create Date: 2026-02-11 12:12:15.599592

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c8d981fb65cd'
down_revision = '24418579b705'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.LargeBinary(),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('verification_accuracy', sa.Numeric(precision=5, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('verification_accuracy')
        batch_op.drop_column('verified')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.LargeBinary(),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=False)

    # ### end Alembic commands ###
