"""empty message

Revision ID: d115ce07e4f2
Revises: 61e84852dc0b
Create Date: 2025-11-17 22:18:13.442786

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd115ce07e4f2'
down_revision = '61e84852dc0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(length=3),
               type_=sa.String(length=5),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.String(length=5),
               type_=mysql.VARCHAR(length=3),
               existing_nullable=False)

    # ### end Alembic commands ###
