"""empty message

Revision ID: dfe33f4545f6
Revises: 21315fd27786
Create Date: 2025-11-23 16:15:07.492232

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dfe33f4545f6'
down_revision = '21315fd27786'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('short_title',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('short_type',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('short_type',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('short_title',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
