"""empty message

Revision ID: f121eead97a9
Revises: 
Create Date: 2026-01-23 19:07:01.654437

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f121eead97a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subscription_json', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_helpers', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('end_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('minimum_helpers')
        batch_op.drop_column('maximum_helpers')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maximum_helpers', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('minimum_helpers', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_column('end_date')
        batch_op.drop_column('number_of_helpers')

    op.drop_table('subscriptions')
    # ### end Alembic commands ###
